/** MAISON JF® | O Farol — Maison 2 candidate */
(function(){
'use strict';
function track(name,parameters={}){if(window.maisonAnalytics&&typeof window.maisonAnalytics.track==='function')window.maisonAnalytics.track(name,parameters);}
const result=(title,text,href,label,href2=null,label2=null)=>({title,text,cta:{href,text:label},cta2:href2&&label2?{href:href2,text:label2}:null});
const product=slug=>`/produtos/${encodeURIComponent(slug)}/`;
const products='/produtos/';
const services='/servicos/';
const test='/teste/';
const contact='/contacto/';
const data={step1:{
 decisao:{question:'O que é que te mantém no mesmo sítio?',options:[{key:'voltas',label:'Já pensei em tudo. Continuo sem conseguir decidir.'},{key:'medo',label:'No fundo eu sei o que quero. Tenho medo de me arrepender.'},{key:'urgente',label:'Preciso de decidir isto antes que me consuma outra semana.'}]},
 relacao:{question:'Quando essa pessoa te volta à cabeça, o que acontece?',options:[{key:'cabeca',label:'Vou outra vez às mensagens, às redes ou à conversa que tivemos.'},{key:'decidir',label:'Não sei se insisto, desisto ou espero.'},{key:'entender',label:'Quero perceber se estou a ver isto como é ou como queria que fosse.'}]},
 cansaco:{question:'Onde é que já não estás a conseguir?',options:[{key:'corpo',label:'Chego ao fim do dia e até cuidar de mim dá trabalho.'},{key:'cabeca',label:'Deito-me e a cabeça continua a trabalhar.'},{key:'demais',label:'Acordo cansado(a). Isto já não é de hoje.'}]},
 casa:{question:'Quando entras em casa, o que gostavas que mudasse primeiro?',options:[{key:'cheiro',label:'Quero entrar e sentir logo outro ar.'},{key:'parar',label:'Quero entrar e sentir logo: acabou por hoje.'},{key:'mudar',label:'Quero sentir a casa diferente sem mexer na casa toda.'}]},
 trabalho:{question:'O que está a pesar mais?',options:[{key:'mudar',label:'Quero mudar, mas tenho medo de trocar o certo pelo errado.'},{key:'peso',label:'O trabalho acaba. O peso vem comigo.'},{key:'projeto',label:'Há um projecto meu parado e não sei se insisto ou largo.'}]},
 dinheiro:{question:'O que é que o dinheiro está a fazer contigo?',options:[{key:'medo',label:'Mesmo quando não estou a fazer contas, continuo a fazê-las por dentro.'},{key:'decisao',label:'Tenho uma decisão financeira e não consigo parar de dar voltas.'},{key:'travao',label:'Tudo o que quero fazer começa por “quando tiver dinheiro…”.'}]},
 eu:{question:'Onde é que a dúvida entra?',options:[{key:'aprovacao',label:'Só descanso quando alguém confirma que fiz bem.'},{key:'comparacao',label:'Basta olhar para outra pessoa e já parece que estou atrasado(a).'},{key:'padrao',label:'Mudo o cenário. Acabo outra vez no mesmo sítio.'}]},
 aprender:{question:'O que estás cansado(a) de adiar?',options:[{key:'tarot',label:'Quero aprender Tarot a sério.'},{key:'astrologia',label:'Quero perceber Astrologia sem decorar frases feitas.'},{key:'outra',label:'Quero aprender outra coisa, mas ainda nem sei por onde começar.'}]},
 companhia:{question:'O que te está a faltar nesse plano?',options:[{key:'evento',label:'Tenho um convite. O que me custa é chegar sozinho(a).'},{key:'sair',label:'Quero fazer o plano. Sozinho(a), sei que vou desistir.'},{key:'falar',label:'Quero sair, conversar e ter alguém ali comigo. Sem romance.'},{key:'afecto',label:'Hoje queria proximidade, carinho e um pouco de romance.'}]},
 presente:{question:'O que não queres que a prenda pareça?',options:[{key:'qualquer',label:'Uma coisa qualquer comprada no caminho.'},{key:'casa',label:'Quero algo bonito para a casa que a pessoa use mesmo.'},{key:'corpo',label:'Quero oferecer uma pausa, não mais uma coisa.'}]},
 outro:{question:'O que é mais fácil agora?',options:[{key:'ver',label:'Mostra-me o que existe.'},{key:'falar',label:'Prefiro explicar o que se passa a uma pessoa.'}]}
},results:{
 decisao_voltas:result('Já fizeste listas. Continuas no mesmo sítio.','Se queres começar pequeno, abre Escolhas & Mudança por 2 €. Se a decisão precisa do teu contexto, leva-a a uma Consulta de Tarot.', '/oraculo/escolhas','Abrir Escolhas · 2 €','/contacto/?interesse=tarot','Levar à Consulta · 35 €'),
 decisao_medo:result('Saber o que queres não apaga o medo de te arrependeres.','Uma abertura simbólica em Escolhas & Mudança custa 2 €. Se precisares de trabalhar a tua situação concreta, a Consulta de Tarot custa 35 €.', '/oraculo/escolhas','Abrir Escolhas · 2 €','/contacto/?interesse=tarot','Quero olhar para o meu caso · 35 €'),
 decisao_urgente:result('Não queres levar isto contigo para outra semana.','Quando a resposta depende do teu contexto, traz a pergunta concreta. A Consulta de Tarot custa 35 € e serve precisamente para olhar para aquilo que uma resposta genérica não consegue conhecer.',services,'Quero olhar para isto · 35 €'),
 relacao_cabeca:result('Dizes que já passou. Depois vais outra vez ver se escreveu.','Se queres começar sem contar a história toda, abre Amor & Relações por 2 €. Se isto depende dos detalhes que só tu conheces, leva o caso a Consulta.', '/oraculo/amor','Abrir Amor & Relações · 2 €','/contacto/?interesse=tarot','Olhar para o meu caso · 35 €'),
 relacao_decidir:result('O pior é não saber se esperas ou vais embora.','Começa por Relações Indefinidas, uma abertura de 2 €. Se precisares de trabalhar a tua situação concreta, leva-a a Consulta.', '/oraculo/relacoes-indefinidas','Abrir Relações Indefinidas · 2 €','/contacto/?interesse=tarot','Quero perceber o que fazer · 35 €'),
 relacao_entender:result('Estás cansado(a) de tentar perceber o que isto significa.','Em vez de adivinhar a cabeça da outra pessoa, começa pelo que esta ligação está a fazer contigo. Podes abrir Amor & Relações por 2 € ou trazer o caso completo para Consulta.', '/oraculo/amor','Abrir Amor & Relações · 2 €','/contacto/?interesse=tarot','Levar o caso à Consulta · 35 €'),
 cansaco_corpo:result('Até cuidar de ti parece mais uma tarefa.','Então não compliques. Começa pequeno: Escalda-Pés MAISON JF®, 150 g, 5 €. Água morna, alguns minutos e um gesto concreto que marca a pausa. Se depois perceberes que precisas de mais do que um ritual, tens Acompanhamento.',product('escalda-pes'),'Quero o Escalda-Pés · 5 €',services,'Ver Acompanhamento'),
 cansaco_cabeca:result('Deitaste o corpo. A cabeça continua em pé.','Muda primeiro o momento. Uma Vela Aromática, tamanho maior, 14 €, pode marcar a passagem entre o dia e a noite com luz e aroma. Se o que continua ligado é maior do que o ritual, o passo seguinte pode ser Acompanhamento.',product('vela-vidro'),'Quero marcar o fim do dia · 14 €',services,'Ver Acompanhamento'),
 cansaco_demais:result('Já não parece ser só o cansaço de hoje.','Podes começar por uma pausa concreta sem transformar isso numa promessa de cura: Escalda-Pés, 5 €. E se o que estás a carregar pede continuidade, vê os Acompanhamentos da Maison.',product('escalda-pes'),'Começar por mim · 5 €',services,'Preciso de mais acompanhamento'),
 casa_cheiro:result('Queres entrar e sentir logo outro ar.','A Névoa muda o aroma do espaço de forma imediata. Está no catálogo actual por 6,50 €.',product('nevoa'),'Quero mudar o ar · 6,50 €',products,'Comparar Produtos'),
 casa_parar:result('Queres que a casa te diga: acabou por hoje.','Cria um marcador simples. A Vela Aromática maior custa 14 € e junta luz, aroma e atmosfera; se quiseres levar a pausa para o corpo, o Escalda-Pés custa 5 €.',product('vela-vidro'),'Quero a Vela · 14 €',product('escalda-pes'),'Juntar Escalda-Pés · 5 €'),
 casa_mudar:result('Não queres obras. Queres sentir a casa diferente.','Começa pelo que muda depressa: aroma. A Névoa custa 6,50 €. Se preferires luz e aroma, as Velas Aromáticas existem em dois tamanhos, 8 € e 14 €.',product('nevoa'),'Quero a Névoa · 6,50 €',products,'Ver Produtos'),
 trabalho_mudar:result('Já percebeste que ficar também é uma escolha.','Começa por Trabalho & Caminho: uma abertura simbólica custa 2 €. Se precisares de olhar para a tua situação concreta, o Tarot Expresso custa 17 €.', '/oraculo/trabalho','Abrir Trabalho & Caminho · 2 €','/contacto/?interesse=tarot-expresso','Tarot Expresso · 17 €'),
 trabalho_peso:result('O trabalho acaba no relógio. O peso não.','Abre Trabalho & Caminho por 2 €. Se o que precisas é dizer tudo e pôr por ordem sem Tarot, a Escuta Orientada custa 60 €.', '/oraculo/trabalho','Abrir Trabalho & Caminho · 2 €','/contacto/?interesse=escuta','Escuta Orientada · 60 €'),
 trabalho_projeto:result('Há um projecto parado e uma decisão por tomar.','Podes começar por Trabalho & Caminho por 2 €. Se queres estrutura para sair do ponto morto, a Mentoria começa nos 125 €.', '/oraculo/trabalho','Abrir Trabalho & Caminho · 2 €','/contacto/?interesse=mentoria','Perguntar pela Mentoria'),
 dinheiro_medo:result('Mesmo quando não estás a fazer contas, continuas a fazê-las por dentro.','Dinheiro & Segurança é uma abertura simbólica de 2 €. Não é aconselhamento financeiro; serve para olhar para a forma como estás a viver a questão.', '/oraculo/dinheiro','Abrir Dinheiro & Segurança · 2 €'),
 dinheiro_decisao:result('Uma decisão financeira não fica mais fácil só porque pensas nela pela centésima vez.','Os factos vêm primeiro. Se queres outra perspectiva simbólica sem a confundir com aconselhamento financeiro, abre Dinheiro & Segurança por 2 €.', '/oraculo/dinheiro','Abrir Dinheiro & Segurança · 2 €'),
 dinheiro_travao:result('Tudo começa por “quando tiver dinheiro…”.','Abre Dinheiro & Segurança por 2 €. Se o bloqueio está ligado a um projecto e precisas de estrutura para avançar, pergunta pela Mentoria.', '/oraculo/dinheiro','Abrir Dinheiro & Segurança · 2 €','/contacto/?interesse=mentoria','Perguntar pela Mentoria'),
 eu_aprovacao:result('Só fica certo depois de alguém dizer que está certo.','Aprovação & Validação é uma abertura de 2 €. Se esta dúvida precisa do teu contexto, o Tarot Expresso custa 17 €.', '/oraculo/necessidade-aprovacao','Abrir Aprovação & Validação · 2 €','/contacto/?interesse=tarot-expresso','Tarot Expresso · 17 €'),
 eu_comparacao:result('A vida dos outros parece sempre estar a acontecer mais depressa.','Abre Comparação & Inveja por 2 € e olha para aquilo que a comparação está a mexer em ti, sem transformar a vida de outra pessoa numa medida da tua.', '/oraculo/comparacao-inveja','Abrir Comparação & Inveja · 2 €'),
 eu_padrao:result('Mudam as pessoas. Muda o cenário. A sensação volta.','Eu & Padrões é uma abertura de 2 €. Se queres trabalhar o teu caso com mais contexto, podes levá-lo a Consulta.', '/oraculo/padroes','Abrir Eu & Padrões · 2 €','/contacto/?interesse=tarot','Levar à Consulta · 35 €'),
 aprender_tarot:result('Queres aprender Tarot a sério.','Então a próxima etapa não é mais uma frase solta: pergunta pelos formatos de Acompanhamento e aprendizagem disponíveis na Maison.',services,'Quero saber como aprender'),
 aprender_astrologia:result('Queres perceber Astrologia sem decorar frases feitas.','Diz-nos o que queres aprender ou receber. Confirmamos o formato realmente disponível antes de te vender alguma coisa.',contact,'Perguntar à Maison'),
 aprender_outra:result('Queres começar. Ainda não sabes por onde.','Não precisas de escolher um curso às cegas. Diz-nos o que queres aprender e vemos se existe um formato de Mentoria que faça sentido.', '/contacto/?interesse=mentoria','Perguntar pela Mentoria'),
 companhia_evento:result('Já tens o convite. O que pesa é chegares sozinho(a).','A Companhia pode ser combinada para um café, passeio, evento ou outro momento acordado. Vê o serviço e pergunta disponibilidade.',services,'Quero Companhia'),
 companhia_sair:result('Queres fazer o plano. Sozinho(a), sabes que podes desistir.','Se o plano continua a apetecer-te e o que falta é presença, começa pela Companhia e combina previamente o formato e os limites.',services,'Perguntar disponibilidade'),
 companhia_falar:result('Queres conversa e presença. Não um encontro.','A Companhia pode ser tempo partilhado, conversa e uma actividade combinada. Não precisa de fingir outra coisa para ter valor.',services,'Quero Companhia'),
 companhia_afecto:result('Queres proximidade. Então os limites têm de estar claros.','Vê os formatos de Companhia disponíveis e combina previamente o que faz parte do serviço. Não é um serviço sexual nem uma promessa de relação.',services,'Ver Companhia'),
 presente_qualquer:result('Não queres entregar uma coisa comprada só para cumprir.','Escolhe pelo momento que queres oferecer: casa, aroma, luz ou pausa. O catálogo começa nos 5 €.',products,'Encontrar um presente'),
 presente_casa:result('Queres algo bonito para a casa que a pessoa use mesmo.','Podes escolher uma Vela Aromática, 8 € ou 14 €, ou a Névoa, 6,50 €, para uma mudança de aroma imediata.',products,'Escolher presente para a casa'),
 presente_corpo:result('Queres oferecer uma pausa, não mais uma coisa.','Começa pelo Escalda-Pés, 150 g, 5 €. Se a pessoa gosta de toque e massagem, o Óleo de Massagem começa nos 12 €.',product('escalda-pes'),'Quero oferecer a pausa · 5 €',product('oleo-massagem'),'Prefiro Óleo de Massagem'),
 outro_ver:result('Sem problema. Vai directo ao que existe.','Se já sabes o tipo de coisa que procuras, explora a Maison. Se queres uma experiência simbólica curta, o Oráculo começa nos 2 €.', '/#explorar-maison','Explorar a Maison','/oraculo/','Abrir o Oráculo · 2 €'),
 outro_falar:result('Às vezes é mais fácil explicar do que escolher.','Fala connosco em português normal. Se a Maison tiver uma opção que faça sentido, mostramos-ta; se não tiver, não inventamos.',contact,'Falar com a Maison')
}};
let currentStep=1,step1Choice=null,step2Choice=null;const steps={1:document.getElementById('farolStep1'),2:document.getElementById('farolStep2'),3:document.getElementById('farolStep3')};const dots=document.querySelectorAll('.farol__progress-dot'),q=document.getElementById('farolStep2Question'),opts=document.getElementById('farolStep2Options'),out=document.getElementById('farolResult'),back2=document.getElementById('farolBack2'),back3=document.getElementById('farolBack3');
function progress(step){dots.forEach((dot,i)=>dot.classList.toggle('farol__progress-dot--active',i<step));}function show(step){Object.values(steps).forEach(el=>el&&el.classList.remove('farol__step--active'));if(!steps[step])return;steps[step].classList.add('farol__step--active');currentStep=step;progress(step);}function build(key){const d=data.step1[key];if(!d||!q||!opts)return;step1Choice=key;track('farol_start',{theme:key,page_path:location.pathname});q.textContent=d.question;opts.innerHTML='';d.options.forEach(o=>{const b=document.createElement('button');b.className='farol__option';b.type='button';b.innerHTML=`<span class="farol__option-text">${o.label}</span><span aria-hidden="true">→</span>`;b.addEventListener('click',()=>choose(o.key));opts.appendChild(b);});show(2);}function choose(key){step2Choice=key;track('farol_refine',{theme:step1Choice,choice:key,page_path:location.pathname});render(data.results[`${step1Choice}_${key}`]||result('Não te vou inventar uma resposta.','Explica-nos o que procuras. Se houver uma solução real, dizemos-te qual.',contact,'Falar com a Maison'));}function render(r){if(!out)return;const external=h=>/^https?:/.test(h)?' target="_blank" rel="noopener"':'';out.innerHTML=`<h3 class="farol__result-title">${r.title}</h3><p class="farol__result-text">${r.text}</p><div class="farol__result-actions"><a href="${r.cta.href}" class="btn btn--primary"${external(r.cta.href)} data-farol-cta="primary">${r.cta.text}</a>${r.cta2?`<a href="${r.cta2.href}" class="btn btn--secondary"${external(r.cta2.href)} data-farol-cta="secondary">${r.cta2.text}</a>`:''}</div>`;track('farol_result',{theme:step1Choice||'unknown',choice:step2Choice||'unknown',destination:r.cta.href,page_path:location.pathname});show(3);}function reset(){track('farol_restart',{page_path:location.pathname});step1Choice=null;step2Choice=null;show(1);}if(steps[1])steps[1].querySelectorAll('[data-farol]').forEach(b=>b.addEventListener('click',()=>build(b.getAttribute('data-farol'))));if(out)out.addEventListener('click',e=>{const a=e.target.closest('[data-farol-cta]');if(a)track('farol_cta_click',{theme:step1Choice||'unknown',choice:step2Choice||'unknown',cta_position:a.dataset.farolCta||'primary',destination:a.getAttribute('href')||'',page_path:location.pathname});});if(back2)back2.addEventListener('click',()=>show(1));if(back3)back3.addEventListener('click',reset);window.Farol={data,reset,getState:()=>({step:currentStep,step1:step1Choice,step2:step2Choice})};
})();